/**
 * Generated by scripts/generate-bloom-frames.mjs. Do not edit by hand.
 * Captions and order live in lib/bloom.ts.
 */
export const BLOOM_SOURCES = [
  {
    slug: "roses-green-trick",
    sample: "/bloom/roses-green-trick.webp",
    poster: "/bloom/roses-green-trick-poster.webp",
    width: 1200,
    height: 1600,
    blurDataURL: "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAwAgCdASoMABAAA4BaJbACdAYvNnY97DbWAADONsLfUNXibxbC6zsCausOHM/7JHVqqEOhjHvSRrfpmaCn6JA2fz2Z+G4alOSgPstiIeJe0FpZVYfS65lalRL/NHLbKskHLvTjCW9xA2C2tAsWXESFAmL8vD+hgmbjrjS05ia2OWgA",
  },
  {
    slug: "roses-hellebore",
    sample: "/bloom/roses-hellebore.webp",
    poster: "/bloom/roses-hellebore-poster.webp",
    width: 1200,
    height: 1600,
    blurDataURL: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQAgCdASoMABAAA4BaJbACdAD0EuEUW6hMAP7V7ERb27U40ebz7VXQTUUSjNjwlAC55bVxE9aIrVopvAJ28y7zAR0oJERtmoSen0nKJY78Nx4UiSJsr92R381W+pjsj81ePQPlU6OcCS9DfgbT4awA",
  },
  {
    slug: "cooler-doors",
    sample: "/bloom/cooler-doors.webp",
    poster: "/bloom/cooler-doors-poster.webp",
    width: 1200,
    height: 1600,
    blurDataURL: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoMABAAA4BaJbACdADhHU60IQ0AAPhF8XDITdrmqf6bg9H/F1d0GLk2bmiDPkzem6uvlV1hWFeDwreoUKUiu5oGAITiy3DYXcXtPHqDEvQXFW9XIYdAzqrU7YAAAA==",
  },
] as const;
