/**
 * Generated by scripts/generate-bloom-frames.mjs. Do not edit by hand.
 * Captions and order live in lib/bloom.ts.
 */
export const BLOOM_SOURCES = [
  {
    slug: "roses-green-trick",
    sample: "/bloom/roses-green-trick.webp",
    poster: "/bloom/roses-green-trick-poster.webp",
    width: 1200,
    height: 1600,
    blurDataURL: "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwAgCdASoMABAAA4BaJbACdGuADz5NVXIbE08AAP4HecIebr3Y7UreiGeKW7rDxP73ZR4913AMHtbgV80hYFc2v54f7pOrpGWT8zpjzJitU0EcLVcO2ntz6o/GxkrcHHVcx7SpNpnIwYJ8SXwP88tezWRGBUJ/d0KmN2AXuUWPFUWKUN4unmjZcwAAAA==",
  },
  {
    slug: "roses-hellebore",
    sample: "/bloom/roses-hellebore.webp",
    poster: "/bloom/roses-hellebore-poster.webp",
    width: 1200,
    height: 1600,
    blurDataURL: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABwAgCdASoMABAAA4BaJbACdAdwLfNttMuFKS4AAP6VDJcGNw675XmmYYHgRGzjhRcbaJlVN/q+e4J/3zEpScZPz38nY3lVr8qq05WrtLmvpEM/ixk4ndPJ3Hv5QEXrPKYyGCVxKKPF8+QA+D36H+qadYOcpyuwoKHAAA==",
  },
  {
    slug: "cooler-doors",
    sample: "/bloom/cooler-doors.webp",
    poster: "/bloom/cooler-doors-poster.webp",
    width: 1200,
    height: 1600,
    blurDataURL: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoMABAAA4BaJbACdADhHU60IQ0AAPhF8XDITdrmqf6bg9H/F1d0GLk2bmiDPkzem6uvlV1hWFeDwreoUKUiu5oGAITiy3DYXcXtPHqDEvQXFW9XIYdAzqrU7YAAAA==",
  },
] as const;
